name: Release
on:
  release:
    types:
      - created
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/386, linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/386, windows/amd64, windows/arm64'
          package: ''
          name: 'discropalypse'
          compress: 'false'
          dest: 'build'
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: ${{ github.ref }}
          file_glob: true
